Rework
Most important changes:
 - code clean-up
 - add caching
 - add better lyrics formatting

diff --git a/cmus-lyrics b/cmus-lyrics
--- a/cmus-lyrics
+++ b/cmus-lyrics
@@ -1,150 +1,193 @@
 #!/usr/bin/env bash
 
-if ! type cmus >/dev/null 2>&1; then
+CACHE_BASEDIR="${HOME}/.cache/cmus"
+TOOLS_NEEDED=(
+    cmus
 
-printf "\033c"
-echo ""
-echo "Cmus Is Not Installed!"
-echo ""
-echo "Cmus Is An Amazing Console Audio Player!"
-echo "Please Install Cmus Using Your Package-manager!"
-echo ""
+    column
+    cut
+    grep
+    perl
+    pr
+    sed
+    vim
+    wget
+)
 
-exit 1
+main() {
+    check_tools_are_installed "${TOOLS_NEEDED[@]}"
+    check_perl_module_escape_is_installed
+    check_lyrics_site_is_available
+    fetch_lyrics
+}
 
-else
+check_tools_are_installed() {
+    local tool
+    for tool in "${@}"; do
+        check_tool_is_installed "${tool}"
+    done
+}
 
-CMUSQ=$(cmus-remote -Q 2>/dev/null)
+check_tool_is_installed() {
+    local tool="${1}"
+    if ! type "${tool}" >/dev/null 2>&1; then
+        printf "\033c"
+        echo ""
+        echo "${tool} is not installed!"
+        echo ""
+        echo "${tool} is a required dependency."
+        echo "Please, install ${tool} using your package manager!"
+        echo ""
 
-if [[ -z "$CMUSQ" ]]; then
+        exit 1
+    fi
+}
 
-printf "\033c"
-echo ""
-echo "Cmus Is Not Running!"
-echo "To Start Cmus, type \"cmus\" In Your Terminal!"
-echo ""
+check_perl_module_escape_is_installed() {
+    perl -MURI::Escape -e 'print "$URI::Escape::VERSION\n";' > /dev/null 2>&1
+    if [ "${?}" -ne 0 ]; then
+        printf "\033c"
+        echo ""
+        echo "Perl module \"URI::Escape\" is not installed!"
+        echo ""
+        echo "Module \"URI::Escape\" is a required dependency!"
+        echo "Please open the following link for more info,"
+        echo ""
+        echo -e '\e[38;5;82m'"http://stackoverflow.com/q/65865"
+        echo ""
+        tput sgr0
 
-exit 1
+        exit 1
+    fi
+}
 
-else
+check_lyrics_site_is_available() {
+    if ! wget -S --spider "https://makeitpersonal.co" 2>&1 | grep -q 'HTTP/1.1 200 OK'; then
+        printf "\033c"
+        echo ""
+        echo "Cannot connect to the site \"makeitpersonal\"!"
+        echo "Make sure your internet connection is active!"
+        tput sgr0
 
-CM_ST=$(cmus-remote -Q 2>/dev/null | grep "stopped")
+        exit 1
+    fi
+}
 
-if [[ -n "$CM_ST" ]]; then
+fetch_lyrics() {
+    while :; do
+        printf "\033c"
 
-printf "\033c"
-echo ""
-echo "Cmus Is Not Playing Anything!"
-echo ""
+        check_cmus_is_running
+        check_cmus_is_playing
 
-exit 1
+        local song_duration
+        song_duration=$(cmus-remote -Q 2>/dev/null | grep -m 1 'duration' | cut -d ' ' -f 2)
+        if [ -z "${song_duration}" ]; then
+            print_header "[No song. Waiting...]"
+            sleep 5
+            continue
+        fi
 
-else
+        local position_in_song
+        position_in_song=$(cmus-remote -Q 2>/dev/null | grep -m 1 'position' | cut -d ' ' -f 2)
+        local sleep_time
+        sleep_time=$((song_duration - position_in_song))
 
-if ! type perl >/dev/null 2>&1; then
+        local artist
+        artist=$(cmus-remote -Q 2>/dev/null | grep -m 1 'artist' | cut -d ' ' -f 3-)
+        local title
+        title=$(cmus-remote -Q 2>/dev/null | grep -m 1 'title' | cut -d ' ' -f 3-)
+        local album
+        album=$(cmus-remote -Q 2>/dev/null | grep -m 1 'album' | cut -d ' ' -f 3-)
 
-printf "\033c"
-echo ""
-echo "Perl Is Not Installed!"
-echo ""
-echo "Perl Is A Required Dependency!"
-echo "Please Install Perl Using Your Package-manager!"
-echo ""
+        local header="$artist ($album) - $title"
+        local cached_lyrics_file=""
 
-exit 1
+        local lyrics
+        if [ -n "${artist}" -a -n "${title}" ]; then
+            if [ -n "${album}" ]; then
+                local cache_dir="${CACHE_BASEDIR}/${artist}/${album}"
+                mkdir -p "${cache_dir}"
+                cached_lyrics_file="${cache_dir}/${title}"
+            fi
 
-else
+            if [ -n "${cached_lyrics_file}" -a -r "${cached_lyrics_file}" ]; then
+                lyrics=$(cat "${cached_lyrics_file}")
+                header="${header} [from cache]"
+            else
+                local artist_escaped
+                artist_escaped=$(echo "$artist" | perl -MURI::Escape -ne 'chomp;print uri_escape($_),"\n"')
+                local title_escaped
+                title_escaped=$(echo "$title" | perl -MURI::Escape -ne 'chomp;print uri_escape($_),"\n"')
+                lyrics=$(wget --user-agent="Mozilla/5.0 Gecko/20100101" --no-check-certificate --quiet --timeout=30 -O - "https://makeitpersonal.co/lyrics?artist=$artist_escaped&title=$title_escaped")
+                if [ -n "${lyrics}" -a "${lyrics}" != "Sorry, We don't have lyrics for this song yet." ]; then
+                    printf "%s" "${lyrics}" > "${cached_lyrics_file}"
+                fi
+            fi
+        else
+            if [ -z "${artist}" ]; then
+                artist="<missing artist>"
+            fi
+            if [ -z "${album}" ]; then
+                album="<missing album>"
+            fi
+            if [ -z "${title}" ]; then
+                title="<missing title>"
+            fi
+            header="$artist ($album) - $title"
+            lyrics="<missing lyrics>"
+        fi
 
-perl -MURI::Escape -e 'print "$URI::Escape::VERSION\n";' &> /dev/null
+        print_header "${header}"
+        print_lyrics "${lyrics}"
 
-RETVAL=$?
+        sleep "${sleep_time}"
+    done
+}
 
-if [ "$RETVAL" -ne 0 ]; then
+check_cmus_is_running() {
+    while :; do
+        local cmusq
+        cmusq=$(cmus-remote -Q 2>/dev/null)
+        if [ -z "${cmusq}" ]; then
+            print_header "[Cmus is not running. To start cmus, type 'cmus' in your terminal. Waiting...]"
+            sleep 5
+            continue
+        else
+            break
+        fi
+    done
+}
 
-printf "\033c"
-echo ""
-echo "Perl Module \"URI::Escape\" Is Not Installed!"
-echo ""
-echo "Module \"URI::Escape\" Is A Required Dependency!"
-echo "Please Open The Following Link For More Info,"
-echo ""
-echo -e '\e[38;5;82m'"http://stackoverflow.com/q/65865"
-echo ""
-tput sgr0
+check_cmus_is_playing() {
+    while :; do
+        local cm_st
+        cm_st=$(cmus-remote -Q 2>/dev/null | grep "stopped")
+        if [ -n "${cm_st}" ]; then
+            print_header "[Cmus is not playing anything. Waiting...]"
+            sleep 5
+            continue
+        else
+            break
+        fi
+    done
+}
 
-exit 1
+print_header() {
+    printf "\033c"
+    echo | pr --header="${*}" --length "$(tput lines)" --page-width "$(tput cols)" --date-format="" |
+    sed 's/[[:space:]]\+Page[[:space:]]\+[[:digit:]]\+$//' |
+    grep -v '^\s*$'
+}
 
-else
+print_lyrics() {
+    echo
+    printf "%s\n" "${*}" |
+    column -c "$(tput cols)" -e 2>/dev/null |
+    sed 's/\s*$//' |
+    vim - --not-a-term -esc '%p|q!' -u NONE |
+    grep -v 'Vim: Reading from stdin...' |
+    sed 's/^/ /'
+}
 
-if ! type wget >/dev/null 2>&1; then
-
-printf "\033c"
-echo ""
-echo "Wget Is Not Installed!"
-echo "Please Install Wget Using Your Package-manager!"
-echo ""
-
-exit 1
-
-else
-
-if [[ `wget -S --spider "https://makeitpersonal.co" 2>&1 | grep 'HTTP/1.1 200 OK'` ]]; then
-
-while :
-do
-#get song duration and current position, calculate sleep time.
-time_song=$(cmus-remote -Q 2>/dev/null | grep -m 1 'duration')
-time_song=${time_song##*' '}
-position=$(cmus-remote -Q 2>/dev/null | grep -m 1 'position')
-position=${position##*' '}
-slp_time=$((time_song-position))
-
-printf "\033c"
-ARTIST1=$(cmus-remote -Q 2>/dev/null | grep -m 1 'artist' | cut -d " " -f 3-)
-TITLE1=$(cmus-remote -Q 2>/dev/null | grep -m 1 'title' | cut -d " " -f 3-)
-ALBUM1=$(cmus-remote -Q 2>/dev/null | grep -m 1 'album' | cut -d " " -f 3-)
-
-
-ARTIST2=$(echo "$ARTIST1" | perl -MURI::Escape -ne 'chomp;print uri_escape($_),"\n"')
-TITLE2=$(echo "$TITLE1" | perl -MURI::Escape -ne 'chomp;print uri_escape($_),"\n"')
-SONG1=$(wget --user-agent="Mozilla/5.0 Gecko/20100101" --no-check-certificate --quiet --timeout=30 -O - "https://makeitpersonal.co/lyrics?artist=$ARTIST2&title=$TITLE2")
-
-printf "$TITLE1 - $ARTIST1 - $ALBUM1\n$SONG1"
-
-sleep $slp_time
-
-done
-
-else
-
-printf "\033c"
-echo ""
-echo "Can Not Connect To The Site \"makeitpersonal\"!"
-echo "Make Sure Your Internet Connection Is Active!"
-echo "If The Problem Persists You Can Report It At,"
-echo "GitHub repository of the project by creating,"
-echo "An Issue There. Here Is The Link To The Repo,"
-echo ""
-echo -e '\e[38;5;82m'"https://github.com/hakerdefo/cmus-lyrics"
-echo ""
-tput sgr0
-echo "If you don't use GitHub you can report it by,"
-echo "emailing the author at the following address,"
-echo ""
-echo -e '\e[38;5;82m'"hakerdefo (at) gmail (dot) com"
-echo ""
-tput sgr0
-
-exit 1
-
-
-
-
-
-fi
-fi
-fi
-fi
-fi
-fi
-fi
+main
